hp:
  epochs: 12
  batch_size: 64
  beta:
    sample_type: categorical
    sample_space: [0.1, 0.3, 0.5, 0.7, 0.9]
    default: 1.0
  act_fn:
    sample_type: categorical
    sample_space: [leaky_relu, gelu]
    default: gelu
  optim:
    x:
      lr:
        sample_type: categorical
        sample_space: [5e-1, 2e-1, 1e-1, 5e-2]
        default: 1e-1
      momentum:
        sample_type: categorical
        sample_space: [0.1, 0.5, 0.9, 0.95]
        default: 0.0
    w:
      lr:
        sample_type: categorical
        sample_space: [1e-4, 5e-4]
        default: 1e-4
  T:
    sample_type: categorical
    sample_space: [9, 10]

gpus_per_task: 1.0
direction: maximize